### ISSUE TITLE
Setting the SOCKS5 proxy Port to 9050 didn't work when running Tor

### ISSUE THREAD

**Issue by kezown** [HelgeHunding/guides#1]
In the 'Running Bitcoin Core over Tor' section of the guide, setting the SOCKS5 proxy port to 9050 didn't work for me. Checking the network status with 'getnetworkinfo' in the console showed that everything was connected and reachable, but I wasn't connecting to outside nodes. Changing the port to 9150 fixed the issue. Running on windows 10.

**Comment by DriftwoodPalace** [comment]
Thanks for the feedback! I've updated the text with this:
"
*Troubleshooting:* If you aren't getting any connections (you can see the number of connections by holding your mouse on the network symbol in the bottom right corner or by going to `Help>Debug Window` and change the tab to `Peers`), try changing the port to `9150`. Tor can sometimes use this port on Windows.
"

Seems like Tor sometimes use that port on Windows (or according to this tread https://github.com/bitcoin/bitcoin/issues/2475 if only the browser bundle is used, but that might be outdated).

**Comment by kezown** [comment]
Ah that might be the problem, I think I only installed the browser bundle (or whatever is downloadable from Tor's homepage). Thank you for your contribution to bitcoin @HelgeHunding, doing great stuff!
